# Ansible Playbook for Subutai Dokuwiki blueprint
---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 
    - name: Install tools
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        dpkg_options: force-confdef,force-confold,force-unsafe-io
      with_items: 
        - unzip
        - curl
        - apt-transport-https
        - apache2-utils

    - name: Configure nodesource repo
      copy:
        src: apt/nodesource.list
        dest: /etc/apt/sources.list.d/
        owner: root
        group: root
        mode: 0644

    - name: Add nodesource key
      raw: wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

    - name: Install required debs
      apt: 
        name: "{{ item }}"
        state: latest
        update_cache: yes
        dpkg_options: force-confdef,force-confold,force-unsafe-io
      with_items: 
        - nodejs

    - name: Clean up
      file:
        path: /var/lib/nodered
        state: absent

    - name: Create user
      user:
        name: nodered
        shell: /bin/false
        home: /var/lib/nodered
        create_home: no
        system: yes

    - name: Set file permissions
      file:
        dest: "{{ item }}"
        owner: nodered
        group: nodered
        recurse: yes
      with_items:
        - /var/lib/nodered

    - name: Update npm itself
      npm: 
        name: npm
        global: yes
        state: latest
    
    - name: Install Node-RED with unsafe-perm
      raw: npm install -g --unsafe-perm node-red

    - name: Copy settings.js
      copy:
        src: nodered/settings.js
        dest: /var/lib/nodered/
        owner: nodered
        group: nodered
        mode: 0644

    - name: Set up admin user
      raw: sed -i 's/@ADMIN_USER@/{{ adminUser }}/' /var/lib/nodered/settings.js

    - name: Set up admin password
      raw: sed -i "s/@ADMIN_HASH@/$(htpasswd -bnBC 8 "" {{ adminPassword }} |tr -d ':\n'|sed 's/$2y/$2a/')/" /var/lib/nodered/settings.js

    - name: Copy service files
      copy:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
      with_items:
        - systemd/node-red.service

    - name: Start service
      systemd:
        daemon_reload: yes
        name: node-red.service
        enabled: yes
        state: restarted

# vim: ts=2 et nowrap autoindent
